### ISSUE TITLE
Flutter Outline Doesn't Always Display Outline

### ISSUE THREAD

**Issue by quiverware** [Dart-Code/Dart-Code#2228]
I found this bug when I went to the definition of the Flutter Navigator class. I'm running version 3.7.1 of the Dart and Flutter VSCode extensions.

Steps to reproduce the bug:

1. Click on NavigatorState in my code (the Flutter class probably doesn't matter but this is how I found the bug).
2. The file navigator.dart opens in VSCode. Clicking on the Flutter icon in the sidebar correctly shows an outline for the Flutter / Dart code.
3. Click on a tab of a different file in the editor. In my case, it was one of my project files. An outline of the Flutter / Dart code is properly displayed.
4. Click back on the navigator.dart tab in the editor. The Flutter outline pane is blank.

If I close and reopen the navigator.dart file the Flutter outline is displayed but whenever I click to view another file then click back the navigator.dart Flutter outline is blank.

**Comment by DanTup** [comment]
I think this might be related to an issue I saw and fixed in a7ebb71283a8e1aa00b1f731079b422bb57335d6. Could you see if it's fixed by v3.8.0 Beta 1?

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.8.0-beta.1

Thanks!

**Comment by quiverware** [comment]
Hi Danny,

I installed the v2.8.0-beta 1 Dart extension, verified the beta version was
installed, and restarted VS Code and verified that the problem I'm seeing
still exists. The problem seems to possibly be related to the parsing of
the dart file. What I'm seeing is the first time the Flutter outline for
navigator.dart is displayed in the side bar it's really quick and displays
almost instantly. Leaving the Flutter Outline selected in the side bar, I
click on a different dart file and I see the outline again almost
instantly. I click back on the navigator.dart tab and the Flutter Outline
side bar area is blank but will finally populate with the Flutter outline
after some time. If I go back and forth between the navigator.dart file and
other files, the other files always display their outline almost
instantaneously while the navigator.dart outline is slower and slower
(some times never?) to display. The Flutter outline for navigator.dart is
significantly longer than the other outlines being displayed.

I also tested this in Android Studio 3.5.3, Dart v191.8593, Flutter v42.1.1
and do not see the bug I see in VS Code.

Let me know if you need any additional information.

Michael Jordan
Quiverware LLC

**Comment by DanTup** [comment]
Sorry for the delay in responding. Are you able to reproduce this in a project you can share to see if I can repro?

**Comment by quiverware** [comment]
Hi Danny,

The behavior is really pretty simple to reproduce, at least it is for me.
Try these steps:

   1. Open VS Code
   2. Create a new Flutter project, ex. outline_bug_test
   3. Open the main.dart file in an editor
   4. Open the Flutter widget file navigator.dart in a side editor (the
   side editor isn't necessary just makes it easy)
      - The navigator.dart file is located in the Flutter package at
      packages/flutter/lib/src/widgets/navigator.dart
   5. Click on the Flutter Outline extension in the sidebar
   6. Click back-and-forth between the main.dart file editor and the
   navigator.dart editor

Error behavior: the Flutter outline of the navigator.dart code is slow to
display or never displays. It always displays quickly the first time.
Android Studio does not have this latency problem displaying the
navigator.dart outline. I do not think this is unique to navigator.dart,
it's just a long Dart file. This behavior probably will happen with other
large Dart files.

Does this provide you with enough information to reproduce the bug?

I'm using Dart extension version 3.8.1. Here's my VS Code version
information:

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

Let me know if I can be of further assistance.

Michael Jordan

**Comment by DanTup** [comment]
Thanks! I was able to repro with the steps above. Seems like the way we forced updates for the Outline didn't work for SDK files so it wouldn't work after the first time. We now just read the last outline we had for a file in this case which should resolve the problem.

Thanks!

**Comment by quiverware** [comment]
Hi Danny,

Thanks for the update! I'm glad you were able to find and fix the bug. I
think the fact that Flutter is open source is one of the biggest
understated advantages of Flutter. I'm constantly reading through the
Flutter code to understand the implementation of widgets and improving my
Dart coding abilities by reading the code. The Flutter Outline feature goes
a long way towards making it easy to navigate through the Flutter SDK
widgets. Thank you for fixing this bug and keep up the great work on the
Dart and Flutter extensions for VS Code!

Michael Jordan
Quiverware LLC
