### ISSUE TITLE
LSP code completion should have an option to include parens and/or args

### ISSUE THREAD

**Issue by SametSahin10** [Dart-Code/Dart-Code#2823]
**Describe the bug**
I'm unable to add parenthesis and give parameters to a function using tab to go to the next parameter. 

**To Reproduce**
1. Define a function that accepts one or more parameters.
2. Try to call the function by starting typing it's name and autocompleting it.
3. See that the only thing that is autocompleted is the name of the function.

Below is a recording of my screen that demonstrates the issue.

![Screen Recording 2020-09-27 at 05 35 10](https://user-images.githubusercontent.com/29546660/94354428-94accb00-0083-11eb-88e3-95f7c22f2dae.gif)

**Expected behavior**
Below is a recording of my screen while I autocomplete a simple `console.log()` statement. This is how the autocomplemetion on Dart code should've worked.

![Screen Recording 2020-09-27 at 05 33 24](https://user-images.githubusercontent.com/29546660/94354535-a642a280-0084-11eb-83f5-f0d060928ff0.gif)

`Insert Argument Placeholder` option is enabled and `enableCompletionCommitCharacters` option is disabled.

**Versions (please complete the following information):**
 - VS Code version: 1.49.2
 - Dart extension version: 3.14.1
 - Dart/Flutter SDK version: Dart - 2.9.2 / Flutter - 1.20.4

**Comment by DanTup** [comment]
Do you have the `dart.previewLsp` setting enabled? Right now, for LSP commit characters do not work but the general behaviour for completing on functions is to *not* insert parens, because it's awkward if you don't want to call the function (for example `onTap: _handleTap`).

The expected fix (once commit characters work correctly) is that you press `(` to commit the completion (instead of tab) when you want the parens - that will both commit the highlighted item *and* insert parens. That way it's easy to control whether they're inserted (enter/tab to just get the name, and `(` to invoke).

I couldn't actually repro your TS example - when I complete on `console.log` I also do *not* get the parens. If there's some setting you've set that controls this, perhaps we can align the Dart behaviour+settings with it to make it more discoverable. If you know what this is, please let me know!

**Comment by SametSahin10** [comment]
Yes. I have the `dart.previewLsp` enabled. The way to complete `console.log` statement is to enable `Complete Function Calls` of JS extension. Do commit characters not work right now on **Dart Code** side?

**Comment by JaavierR** [comment]
Following this thread, a moment ago I updated Flutter from version 1.20.3 to 1.22 and it doesn't let me insert the function (classes or widget too) with parenthesis, formerly I could choose between insert only the name of the function/class or the function/class with its parenthesis, is something that was disabled from this version? I found it great to have the option to choose how to use autocompletion rather than having it work only one way, I don't know if it is now activated manually but before this, there was that option by default. Thanks in advance!

I use:
VSCode v.1.49.3
Flutter sdk v.1.22.0
Flutter + Dart Extensions v.3.15.0

**Comment by DanTup** [comment]
Commit characters don't currently work on either LSP or not. I'd like to have them working on LSP, though I hit a problem in VS Code that I haven't fixed yet. Hoping to progress that soon.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8687aa6145c35fae6e1aaa076de7f2a19da7e38c.

When using a new SDK that includes that change, the `dart.completeFunctionCalls` setting will insert parens/required args (as long as commit characters is not enabled).

**Comment by Merrit** [comment]
Fantastic! Thank you for making this a reality. Look forward to trying it ❤️

**Comment by Merrit** [comment]
Should this be available at this point?

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.662], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
[✓] Android Studio (version 4.1.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (5 available)

• No issues found!
```

dart-code 3.17.0

![image](https://user-images.githubusercontent.com/9575627/101219512-24599180-3652-11eb-889d-7519da3ca143.png)

Still isn't adding parentheses or argument placeholders.

**Comment by 2shrestha22** [comment]
> Should this be available at this point?
> 
> ```
> ❯ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.662], locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [✓] Chrome - develop for the web
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
> [✓] Android Studio (version 4.1.0)
> [✓] VS Code (version 1.51.1)
> [✓] Connected device (5 available)
> 
> • No issues found!
> ```
> 
> dart-code 3.17.0
> 
> ![image](https://user-images.githubusercontent.com/9575627/101219512-24599180-3652-11eb-889d-7519da3ca143.png)
> 
> Still isn't adding parentheses or argument placeholders.

Yes same here, still no completion is not working.

**Comment by DanTup** [comment]
@Merrit Have you got the LSP preview enabled, and reloaded VS Code since enabling it? I tested with the same version of Flutter and it seems to be included there:

![Dec-07-2020 11-50-12](https://user-images.githubusercontent.com/1078012/101347746-6e28be80-3882-11eb-8939-a524149428d6.gif)

If you're still not seeing it with LSP enabled, please file a new issue and we can capture some logs to understand what's happening. Thanks!

**Comment by Merrit** [comment]
Double checked LSP seems to be enabled.

This *does* seem to work with something like a function I wrote myself, but not some other things like print() or widgets.

I opened an issue: #2992

**Comment by DanTup** [comment]
Ah, I see. I'll do some digging and follow up in that issue. Thanks!

**Comment by JoyEnergiser** [comment]
I have the same issue, when I disable Dart:Preview LSP then the code completion with parens and/or args works

**Comment by DanTup** [comment]
@JoyEnergiser see [the comment above](https://github.com/Dart-Code/Dart-Code/issues/2823#issuecomment-725630953). There's a new setting to control this in LSP, but it requires an SDK that includes the setting (which is not currently true of Flutter's stable branch, although it should be in the next major stable release).

**Comment by samariotorres** [comment]
still not working for me... tried disabling LS, tried the recommended

**Comment by samariotorres** [comment]
> still not working for me... tried disabling LSP, tried the recommended

Sorry got it working, you have to uncheck commit characters as well.
