### ISSUE TITLE
"Running 'Dart' Formattter" Hangs/Freezes indefinitely

### ISSUE THREAD

**Issue by alex1115alex** [Dart-Code/Dart-Code#2861]
**Describe the bug**
When trying to format Dart code (which is set to happen when I save a .dart file), the Dart Formatter freezes and needs to be canceled.

**To Reproduce**
Run the Dart Formatter by saving a .dart file in Code - OSS.

**Expected behavior**
The Dart Formatter should format my code quickly like it used to do. This file is only 214 lines, so it shouldn't be an issue.

**Screenshots**
https://i.imgur.com/KTJR9wN.png

**Versions:**
 - Code OSS version: 1.49.1
 - Dart extension version: v3.14.1
 - Dart SDK version: 2.9.2 (stable)
 - Flutter version: 1.20.4

**Comment by DanTup** [comment]
Are you able to capture a log when this happens?

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Select only the **Analysis Server** category and click OK
- Reproduce the issue while logging is active
- Stop logging by clicking the **Cancel** button on the logging notification
- Paste the log in a [gist](https://gist.github.com/) or similar and provide the link here

This should capture the format request to the analysis server that might give some clues why it's taking a long time. Note: This log may include parts of your source files so check there's nothing sensitive before sharing.

**Comment by ramtinq** [comment]
This issue exists in a more frequently manner since I updated to 2.13.

**Comment by DanTup** [comment]
@ramtinq are on macOS? You may be hitting a file watcher issue that's been recently fixed (but not made a stable release) - see https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-857536264 for details.

**Comment by ramtinq** [comment]
@DanTup yes I'm using mac OS. Thank you. I'll check it.

**Comment by DanTup** [comment]
The issue mentioned above made it into a stable release of Flutter (v2.2.2), so if you upgrade to that version and restart VS Code, hopefully the issue will be solved.

**Comment by yonycalsin** [comment]
```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hello\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\hello\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\hello\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```

@DanTup  I just today I am experiencing this problem, just a few days ago I installed (android studio, flutter sdk, flutter vscode), and as you can see I have the latest version where supposedly should be solved this problem, I'm still with the problem 😢

**Comment by temitopeog** [comment]
I am also facing the same issue. I have done everything suggested above @DanTup but VS code still hangs / freezes

**Comment by DanTup** [comment]
@temitopeog it's better to open a new issue rather than commenting on the bottom of closed issues when having issues, they're less likely to be missed.

Please file a new issue with as much detail as possible about what you're seeing. If you can help me reproduce it, it should be much easier for me to resolve. Thanks!

**Comment by temitopeog** [comment]
@DanTup ok will do - thanks
