### ISSUE TITLE
Dart formatter Keeps running endlessly

### ISSUE THREAD

**Issue by dewbambs** [Dart-Code/Dart-Code#3270]
Issue Type: <b>Bug</b>

It's random.
At times when you save dart code. Dart formatter starts running and do not stops for several minutes (around 5 minutes minimum). I have to cancel it and save again and same thing happens.
Only solution is restart VScode or sometimes restart the PC.

Extension version: 3.21.1
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.46GB free)|
|Process Argv|--crash-reporter-id fd9ee2dd-443c-41b6-b90c-1cb615a784b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by DanTup** [comment]
Can you confirm which Flutter SDK version you're on, and whether LSP is enabled (hover over the SDK version in the status bar to see whether it says "DAS" or "LSP").

I've seen this before (and a few others have noted it), although I've never been able to get a log file or repro it. If you're able to  [get a log](https://dartcode.org/docs/logging/#analyzer) when this occurs, that may be useful in tracking it down. Thanks!

**Comment by DanTup** [comment]
FWIW - some performance improvements have landed in Flutter master recently that _may_ impact this, though it's hard to be sure since I haven't been able to repro.

**Comment by dewbambs** [comment]
Recently the same issue did not come up. It used to happen when I used Alt + shift + f in VScode. Anytime soon I get the same Issue I will post the logs.

**Comment by DanTup** [comment]
I may have a repro for this.

I'm using SDK:

Loc: /Users/danny/Dev/Dart SDKs/nightly-2021-04-06
Ver: 2.13.0-edge.fc349bdbb5f9c6d4680c11858459abcb96670227

I'm opening the SDK `analysis_server` + `analyzer` packages from the SDK at version e0bfa18c7c6 (using my usual `.code-workspace`) then opening `lib/lsp_protocol/protocol_generated.dart` and making any change and pressing Save.

The file is very large (35k lines) so it might not be the same issue seen on smaller files, but it's definitely way slower than I would expect - 22 seconds in this example (which produced 0 edits because the change was in a comment):

https://gist.github.com/DanTup/05e61e341998ab2c94aed3053899c997

```
# client request formatting (10:23:21.982)
1618478601982:Req:{"jsonrpc"::"2.0","id"::12,"method"::"textDocument/formatting","params"::{"textDocument"::{"uri"::"file::///Users/danny/Dev/Google/dart-sdk/sdk/pkg/analysis_server/lib/lsp_protocol/protocol_generated.dart"},"options"::{"tabSize"::2,"insertSpaces"::true,"insertFinalNewline"::true}}}

# formatting response (10:23:43.529 = 22 seconds)
1618478623529:Res:{"id"::12,"jsonrpc"::"2.0","result"::null}
```

**Comment by DanTup** [comment]
Looks like this time is actually spent in the formatting and not where I thought it might be (generating minimal edits). I'm not sure if this is expected performance though.

@munificent I'm not sure what the expected timings are for a large file like this - it's about 20 seconds for 25k lines. It's definitely a large file (and therefore may be unrelated to the original issue raised here), but I thought it worth checking.

Repo:

```
cd /tmp

curl https://raw.githubusercontent.com/dart-lang/sdk/fc349bdbb5f9c6d4680c11858459abcb96670227/pkg/analysis_server/lib/lsp_protocol/protocol_generated.dart > test.dart

time dart format -o none test.dart

# Formatted 1 file (0 changed) in 20.38 seconds.
```

**Comment by munificent** [comment]
> @munificent I'm not sure what the expected timings are for a large file like this - it's about 20 seconds for 35k lines.

Even very large files should be quite fast to format, but there are corner cases where a file that contains a large number of pathologically complex expressions can get pretty slow.

> Perhaps this 1903 character statement isn't helping (I'm now more convinced this is unrelated to the original issue - I don't think most people have code like this!):
> 
> ```dart
> final documentChanges = (json['documentChanges'] is List && (json['documentChanges'].every((item) => TextDocumentEdit.canParse(item, nullLspJsonReporter))))
>         ? Either2<List<TextDocumentEdit>, List<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>>.t1(
>             json['documentChanges']
>                 ?.map((item) =>
>                     item != null ? TextDocumentEdit.fromJson(item) : null)
>                 ?.cast<TextDocumentEdit>()
>                 ?.toList())
>         : ((json['documentChanges'] is List && (json['documentChanges'].every((item) => (TextDocumentEdit.canParse(item, nullLspJsonReporter) || CreateFile.canParse(item, nullLspJsonReporter) || RenameFile.canParse(item, nullLspJsonReporter) || DeleteFile.canParse(item, nullLspJsonReporter)))))
>             ? Either2<List<TextDocumentEdit>, List<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>>.t2(json['documentChanges']
>                 ?.map((item) => TextDocumentEdit.canParse(item, nullLspJsonReporter)
>                     ? Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>.t1(
>                         item != null ? TextDocumentEdit.fromJson(item) : null)
>                     : (CreateFile.canParse(item, nullLspJsonReporter)
>                         ? Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>.t2(item != null ? CreateFile.fromJson(item) : null)
>                         : (RenameFile.canParse(item, nullLspJsonReporter) ? Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>.t3(item != null ? RenameFile.fromJson(item) : null) : (DeleteFile.canParse(item, nullLspJsonReporter) ? Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>.t4(item != null ? DeleteFile.fromJson(item) : null) : (item == null ? null : (throw '''$item was not one of (TextDocumentEdit, CreateFile, RenameFile, DeleteFile)'''))))))
>                 ?.cast<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>()
>                 ?.toList())
>             : (json['documentChanges'] == null ? null : (throw '''${json['documentChanges']} was not one of (List<TextDocumentEdit>, List<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>)''')));
> ```

You wouldn't believe the things I've seen. That one is definitely pretty bad, but generated code often looks like this and dartfmt is supposed to handle it well.

**Comment by DanTup** [comment]
@munificent is it worth me filing an issue in dart_style about that? (do you think it's likely significant gains could be made?). I could also tweak this generated code (I'm generating it), although my concern was less about this specific file than whether there's a more general issue other users may also see.

If not, I wonder if the analysis server should offload this to another isolate, since it's current synchronous in the main isolate that will block all other requests for the duration (@bwilkerson any thoughts?).

Although, I don't think either of those resolve the original issue here. I'm not sure it's just slow formatting, but suspect the server was busy with something else (perhaps rebuilding contexts it didn't need to - which hopefully is now fixed).

**Comment by bwilkerson** [comment]
If we're sure that dart_style is causing the issue (and not something else in server), then it might well make sense to run `dart_style` asynchronously with a timeout. I'm not convinced that a separate isolate is the right choice because I think that would require parsing the AST again, but I don't have a strong opinion about it either.

**Comment by DanTup** [comment]
> If we're sure that dart_style is causing the issue (and not something else in server)

I'm not sure it's the cause of the original issue raised here - I think I just happened to see the same behaviour but it was caused by the big file. I don't expect many users have code like generated code above, but it would be nice not to improve the experience if they did.

>  it might well make sense to run dart_style asynchronously with a timeout. I'm not convinced that a separate isolate is the right choice because I think that would require parsing the AST again, but I don't have a strong opinion about it either.

If I understand correctly, I think it may be parsing currently anyway?

https://github.com/dart-lang/dart_style/blob/f17c23e0eea9a870601c19d904e2a9c1a7c81470/lib/src/dart_formatter.dart#L116-L121

Is it possible to run dart_style asynchronously? I thought it was all synchronous and CPU bound. If it can be run asynchronously (whether in an isolate or otherwise), I'd prefer to support cancellation than add a timeout (at least for LSP). Timeouts can be frustrating because in some cases users might _want_ to wait for an operation to complete (because the result are more important than it being fast). As long as it's running asynchronously, for LSP we can receive cancellation requests from the client and could abort - that way the user is in control of whether they wait of cancel, rather than it being a fixed time (which could have different cut-offs in terms of file size/complexity based on how powerful the users machine is).

This is probably moot if Bob thinks this could be much faster (in which case I'll file a dart_style issue with the repro above), though otherwise I could file an SDK issue about handling this better and we can figure out the best way there.

I'll leave this issue open for now either way, as I think there's another issue - which may or may not be fixed by the context rebuild changes - that's causing people to see what looks like slow formatting but might not be.

**Comment by bwilkerson** [comment]
> If I understand correctly, I think it may be parsing currently anyway?

Yes, it looks that way. I'd assumed that we'd ask the `AnalysisSession` for the parsed AST and that it would most likely be cached because it would be a priority file. But that assumption appears to have been wrong.

> Is it possible to run dart_style asynchronously?

Probably not.

> ... for LSP we can receive cancellation requests ...

The legacy protocol doesn't support that, so we might have to have a timeout there, or just let the client (IntelliJ) handle the timeout.

**Comment by DanTup** [comment]
> The legacy protocol doesn't support that, so we might have to have a timeout there, or just let the client (IntelliJ) handle the timeout.

Is there a way to time out synchronous code? If not, presumably an isolate would be the only way? (and then it probably wouldn't really be cancelled, but rather us just returning early and it finishing in the background). If we do decide it needs a timeout, it shouldn't be difficult to add to just the non-LSP protocol and use cancellation for LSP (or at least, have a higher timeout for LSP).

We can revisit when it's clearer whether this is a common case (I suspect not) and whether there are optimisations dart_style could make for code like the above. I think may "repro" above is likely an edge case and a bit of a red herring.

**Comment by munificent** [comment]
> @munificent is it worth me filing an issue in dart_style about that?

Yes, please do.

> (do you think it's likely significant gains could be made?).

Yeah, it's definitely possible, though I can't promise when I'll have time to look into it.

> I could also tweak this generated code (I'm generating it), although my concern was less about this specific file than whether there's a more general issue other users may also see.

Tweaking the code would definitely be a good idea. That's a *huge* expression, and a giant generated file that contains many many expressions that large is basically the worst case for dartfmt.

If you generate code like:

```dart
final documentChanges = () {
  if (json['documentChanges'] is List &&
      (json['documentChanges'].every(
          (item) => TextDocumentEdit.canParse(item, nullLspJsonReporter)))) {
    return Either2<
        List<TextDocumentEdit>,
        List<
            Either4<TextDocumentEdit, CreateFile, RenameFile,
                DeleteFile>>>.t1(json['documentChanges']
        ?.map((item) => item != null ? TextDocumentEdit.fromJson(item) : null)
        ?.cast<TextDocumentEdit>()
        ?.toList());
  } else if (json['documentChanges'] is List &&
      (json['documentChanges'].every((item) =>
          (TextDocumentEdit.canParse(item, nullLspJsonReporter) ||
              CreateFile.canParse(item, nullLspJsonReporter) ||
              RenameFile.canParse(item, nullLspJsonReporter) ||
              DeleteFile.canParse(item, nullLspJsonReporter))))) {
    return Either2<
        List<TextDocumentEdit>,
        List<
            Either4<TextDocumentEdit, CreateFile, RenameFile,
                DeleteFile>>>.t2(json['documentChanges']
        ?.map((item) {
          if (TextDocumentEdit.canParse(item, nullLspJsonReporter)) {
            return Either4<TextDocumentEdit, CreateFile, RenameFile,
                    DeleteFile>.t1(
                item != null ? TextDocumentEdit.fromJson(item) : null);
          } else if (CreateFile.canParse(item, nullLspJsonReporter)) {
            return Either4<TextDocumentEdit, CreateFile, RenameFile,
                DeleteFile>.t2(item != null ? CreateFile.fromJson(item) : null);
          } else if (RenameFile.canParse(item, nullLspJsonReporter)) {
            return Either4<TextDocumentEdit, CreateFile, RenameFile,
                DeleteFile>.t3(item != null ? RenameFile.fromJson(item) : null);
          } else if (DeleteFile.canParse(item, nullLspJsonReporter)) {
            return Either4<TextDocumentEdit, CreateFile, RenameFile,
                DeleteFile>.t4(item != null ? DeleteFile.fromJson(item) : null);
          } else if (item == null) {
            return null;
          } else {
            throw '''$item was not one of (TextDocumentEdit, CreateFile, RenameFile, DeleteFile)''';
          }
        })
        ?.cast<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>()
        ?.toList());
  } else if (json['documentChanges'] == null) {
    return null;
  } else {
    throw '''${json['documentChanges']} was not one of (List<TextDocumentEdit>, List<Either4<TextDocumentEdit, CreateFile, RenameFile, DeleteFile>>)''';
  }
};
```

Then it will format it about 1200x faster. (That's *times*, not *percent*.)

**Comment by DanTup** [comment]
@munificent thanks! I've raised https://github.com/dart-lang/dart_style/issues/1022 and may see if it's easy to tweak that in future (I don't hand-edit/format this file, but the generation script does format it at the end - so now I realise why that seemed to be taking a while too).

**Comment by DanTup** [comment]
@mellowcello77 a log could be very helpful:

- Run the "Preferences: Open **Workspace** Settings" command from the VS Code command palette
- Set the [`dart.analyzerInstrumentationLogFile`](https://dartcode.org/docs/logging/#analyzer-instrumentation) to a file path for logging (either absolute, or relative like `"logs/analyzer.txt"` which will go in the project folder)
- Reproduce the issue
- Leave the "Saving..." notification up for a minute or so (on the off-chance it's code that's slow to format rather than the server not responding)
- Take a copy of the log file
- (you can then remove the log file setting)

The log file may contain parts of your source code so if it's something you can't share, please open the log file and look for the last few occurrences of `:Res:` near the bottom of the file which should show what request(s) the server last responded to. I'm interested to know what are the few requests (`:Req`) around that time that were _not_ responded to.

If you can repro on a project without sensitive code, feel free to just attach (or email to me at logs@dartcode.org) the lines starting a handful above the last server response. Thanks!

**Comment by netgfx** [comment]
even with no more than 300 lines of flutter code, no conditionals. But system overall low memory (less than 1Gb unallocated) still causes this issue on a daily basis. Could it be that the formatting process requires some system resources to be available at the forefront (even if it doesn't utilize them completely)?

**Comment by mellowcello77** [comment]
One day later and  have not been able to replicate it again. Will post as requested by DanTup soon as it happens again.

**Comment by DanTup** [comment]
@netgfx 

> Could it be that the formatting process requires some system resources to be available at the forefront (even if it doesn't utilize them completely)?

I'm not certain, but I suspect it's probably not the formatter here - I think the server is not responding correctly and then the format requests jut gets stuck (I think it was coincidence that I triggered something similar behaviour by actually having something that formatted slowly).

If this seems to happen after you're just run a debug session and the analysis server appears to _never_ recover, then it could be related to https://github.com/dart-lang/sdk/issues/45996 (which my or may not be specific to macOS), though I don't fully understand what's happening there yet.

**Comment by samandmoore** [comment]
I have not corroborated this, but someone on my team reported that this appears to happen to them when they have Android studio open at the same time as VS Code. I can't easily imagine how that could happen, perhaps some sort of shared resource contention (seems unlikely right?), but I figure it doesn't hurt too much to share that theory. 

I'm also trying to replicate with logging turned on, but haven't had any luck.

**Comment by ilkerulusoy** [comment]
I have deleted `editor.codeActionsOnSave": null` in `settings.json` and my problem fixed. `null` not acceptable.

**Comment by DanTup** [comment]
@ilkerulusoy if you can reproduce that, please file an additional bug. I tried but couldn't repro, and I wouldn't expect that to cause this sort of issue.

**Comment by ilkerulusoy** [comment]
@DanTup i can not repeat. sorry.

**Comment by mwawrusch** [comment]
For me, this happens on a daily basis. It only goes away when I delete the .dart-tools folder. It's to the point where it is a major distraction.

**Comment by edgarfroes** [comment]
It seems to happen a lot less on Flutter 2.0.6.
Temporary solution that worked to me:

- Navigate your flutter folder;
- Execute `git checkout 2.0.6`;
- Execute `flutter doctor` to download binaries;
- Go back to work.

**Comment by brianschardt** [comment]
happening to my and half my team on flutter 2.2 this is very frustrating. none of the fixes above worked.

**Comment by edgarfroes** [comment]
It happens to me only when using iOS simulator or iOS physical device. Works fine on Android emulator, haven't teste on Android physical device.

**Comment by leidig54** [comment]
> I have deleted `editor.codeActionsOnSave": null` in `settings.json` and my problem fixed. `null` not acceptable.

This fixed it for me. Having "null" raised a warning that an object was expected. Make sure to restart VSCode after.

**Comment by DanTup** [comment]
@leidig54 if you can reproduce that, please file an additional bug. I tried but couldn't repro, and I wouldn't expect that to cause this sort of issue.

I'm still really interested in a log file of this happening (see my notes above - https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-847887577). I've not been able to reproduce this so seeing the requests that the server last responded to when this happened may help understand what's going on. Thanks!

**Comment by leidig54** [comment]
> @leidig54 if you can reproduce that, please file an additional bug. I tried but couldn't repro, and I wouldn't expect that to cause this sort of issue.
> 
> I'm still really interested in a log file of this happening (see my notes above - [#3270 (comment)](https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-847887577)). I've not been able to reproduce this so seeing the requests that the server last responded to when this happened may help understand what's going on. Thanks!

I spoke too soon - issue back again. I have captured it on the logs and emailed the file to you at the above email address.

**Comment by DanTup** [comment]
@leidig54 thanks for the log! I'm pretty certain that for the log you sent me you're hitting https://github.com/dart-lang/sdk/issues/45996 which was fixed a few days ago. The analysis server stops responding while the Flutter app was being built, which looks like the same deadlock issue to me (it causes the analysis server to become unresponsive).

**Comment by leidig54** [comment]
> @leidig54 thanks for the log! I'm pretty certain that for the log you sent me you're hitting [dart-lang/sdk#45996](https://github.com/dart-lang/sdk/issues/45996) which was fixed a few days ago. The analysis server stops responding while the Flutter app was being built, which looks like the same deadlock issue to me (it causes the analysis server to become unresponsive).

Thanks for the help. Do we need to be on the Flutter master channel to have this fixed?

**Comment by DanTup** [comment]
@leidig54 I do believe that fix has only made the master channel so far (I wouldn't recommend using master for production work though).

**Comment by smasinde** [comment]
> I have deleted `editor.codeActionsOnSave": null` in `settings.json` and my problem fixed. `null` not acceptable.

This, but I just replaced null with an empty object {}

**Comment by mellowcello77** [comment]
@DanTup Managed to replicate issue today. Log file sent to logs@dartcode.org
editor.codeActionsOnSave": null or {} suggested by other did not work for me.

**Comment by DanTup** [comment]
@mellowcello77 thanks! When you reproduced this, did you start a Flutter build/debug session? The last item in the log is a filesystem event, but it was for `.DS_Store` and nothing else was logged, so it's not as clear if it's the issue linked above, although no format request was logged so it does seem like either a similar problem (in that the request is not going to the server) or something going wrong in the client that's preventing the format request even being sent.

A few things to try:

1. Check Help -> Toggle Developer Tools in VS Code to see if there are any errors in the Console tab
2. Enable the `dart.previewLsp` setting and restart VS Code and see if it repros (and if so, a log file in that mode could be useful too)
3. 
Thanks!

**Comment by mellowcello77** [comment]
@DanTup Yes, it was a new build. I have quite a few build setups, Dev, Demo and Prod for iOS, Android, MacOS and Web. It seems to have been happening for each new build after my flutter upgrade. After stopping the debug session, closing and reopening vscode a few times it seems to go away.

**Comment by DanTup** [comment]
@mellowcello77 got it - in that case I'm fairly sure it's the same issue mentioned above. When you run a Flutter build if it modifies certain types of files (usually in the `.dart_tool` folder) the analyzer rebuilds some internal state that involves removing an old file watcher and adding a new one. That seems to cause an issue (I think a deadlock) that prevented the server from responding to any further requests.

If anyone sees this issue _not on macOS_ or _not after running a Flutter build/debug session_ and can provide a log, that would be useful. If it's macOS after running a debug build, I think it's probably covered by the existing fix.

**Comment by munificent** [comment]
Potentially relevant: https://github.com/microsoft/vscode/issues/107103#issuecomment-731664821

**Comment by ueman** [comment]
I see the same symptons (i.e. formatting hangs, no more code completion,...) when running into https://github.com/dart-lang/sdk/issues/42079 . I'm not sure if it's relevant though.

**Comment by edgarfroes** [comment]
> Potentially relevant: [microsoft/vscode#107103 (comment)](https://github.com/microsoft/vscode/issues/107103#issuecomment-731664821)

This worked for me.

**Comment by fersoer** [comment]
Potentially relevant: microsoft/vscode#107103 (comment)

This really works!

**Comment by ferso** [comment]
Potentially relevant: microsoft/vscode#107103 (comment)

This really works!

**Comment by DanTup** [comment]
> I see the same symptons (i.e. formatting hangs, no more code completion,...) when running into dart-lang/sdk#42079 . I'm not sure if it's relevant though.

It certainly could be the cause for some reports here. Any issue that causes the analysis server not to respond to requests will cause this problem if you have format-on-save enabled, as it will never respond to the format request. That issue seems to be the analysis server stuck walking down cycling symlinks so it never completes (and thus never responds).

If you can reproduce that issue starting from creating a new project, I'd be interested to know though (post on that issue if you can). Although I'm not sure what the solution would be, I did try to figure out the steps that led to those circular symlinks but was unable to repro (so I wasn't sure if it's something that's been fixed and the symlinks are legacy, or if there is something specific that causes the circular symlinks to be created that I didn't do).

**Comment by cheetahcoding** [comment]
This helped me in VS Code:

Uninstall the Flutter extension and Dart extensions then reinstall them. Restart your VS Code

**Comment by DanTup** [comment]
> Uninstall the Flutter extension and Dart extensions then reinstall them. Restart your VS Code

I suspect just restarting VS Code would have the same effect as doing this (and also just running the **Reload Window** command in VS Code), which is restarting the analysis server. Unfortunately I think it's likely only a temporary solution.

For those that are seeing this issue, please do include your Flutter/Dart SDK versions and your OS in your comments, it'll help understand if it's an issue not seen before/fixed.

To summarise:

- A few different issues (circular symlinks and unncessary analysis server context rebuilds) were fixed in Flutter 2.2
- A macOS issue remains in Flutter 2.2 but has been fixed in master (https://github.com/dart-lang/sdk/issues/45996) and there are requests open to cherry-pick to stable (https://github.com/dart-lang/sdk/issues/46249 and https://github.com/dart-lang/sdk/issues/46298).

So I'm particularly interested in any reports from this on Flutter 2.2 or later that are _not_ macOS, or on latest Flutter master (or latest stable if/when those cherry-picks ship there) on any OS.

**Comment by patreu22** [comment]
> > Uninstall the Flutter extension and Dart extensions then reinstall them. Restart your VS Code
> 
> I suspect just restarting VS Code would have the same effect as doing this (and also just running the **Reload Window** command in VS Code), which is restarting the analysis server. Unfortunately I think it's likely only a temporary solution.
> 
> For those that are seeing this issue, please do include your Flutter/Dart SDK versions and your OS in your comments, it'll help understand if it's an issue not seen before/fixed.
> 
> To summarise:
> 
> * A few different issues (circular symlinks and unncessary analysis server context rebuilds) were fixed in Flutter 2.2
> * A macOS issue remains in Flutter 2.2 but has been fixed in master ([dart-lang/sdk#45996](https://github.com/dart-lang/sdk/issues/45996)) and there are requests open to cherry-pick to stable ([dart-lang/sdk#46249](https://github.com/dart-lang/sdk/issues/46249) and [dart-lang/sdk#46298](https://github.com/dart-lang/sdk/issues/46298)).
> 
> So I'm particularly interested in any reports from this on Flutter 2.2 or later that are _not_ macOS, or on latest Flutter master (or latest stable if/when those cherry-picks ship there) on any OS.

Unfortunately I'm having the same issue, but on macOS. Might just leave my SDK versions and OS here, maybe it's helpful :) thx for investigating on that!

macOS 11.4

```
Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    de-DE)
    • Flutter version 2.2.1 at /Users/patrick/Development/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
```

**Comment by DanTup** [comment]
@manojeeva as far as I can tell, that extension adds a new command and doesn't interfere with existing formatting so I suspect it's coincidence.

That said, you're on v2.0.4 of Flutter which definitely has some known bugs that would cause this. If you upgrade to Flutter v2.2 you may find this issue is completely resolved (the outstanding known issue in v2.2 is macOS-only).

**Comment by RAHEYO** [comment]
This comment: [https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-857349415](url)

I uninstalled Flutter, Dart plugin in Visual Studio Code, and then restart IDE, it works magically! But just restarting the IDE does not help, you have to reinstall frameworks too!

**Comment by DanTup** [comment]
[Flutter 2.2.2 has just been released](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#222-june-11-2021) to the stable channel which includes a fix for one of the issues mentioned above (where on macOS the analysis server would stop responding after certain types of files are modified).

Please upgrade to Flutter 2.2.2 and restart all instances of VS Code. If you're still seeing this issue on Flutter 2.2.2 or later, please do let me know. Thanks!

**Comment by Garrison88** [comment]
For the record, the Dart formatter issue is fixed for me as of 2.2.2 (MacOS Big Sur 11.4 VS Code 1.57.0)

**Comment by edgarfroes** [comment]
@DanTup it was stable for a time, but the error persisted to me.

**Comment by DanTup** [comment]
If you're still seeing this with Flutter 2.2.2, a log (see https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-847887577 for instructions) would be very helpful. Thanks!

**Comment by yonycalsin** [comment]
> [Flutter 2.2.2 has just been released](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#222-june-11-2021) to the stable channel which includes a fix for one of the issues mentioned above (where on macOS the analysis server would stop responding after certain types of files are modified).
> 
> Please upgrade to Flutter 2.2.2 and restart all instances of VS Code. If you're still seeing this issue on Flutter 2.2.2 or later, please do let me know. Thanks!

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hello\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\hello\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```

@DanTup  I just today I am experiencing this problem, just a few days ago I installed (android studio, flutter sdk, flutter vscode), and as you can see I have the latest version where supposedly should be solved this problem, I'm still with the problem 😢 

duplicated by https://github.com/Dart-Code/Dart-Code/issues/2861#issuecomment-863747002

**Comment by DanTup** [comment]
@yonycalsin can you reliably trigger this? Are you able to enable [this log file](https://dartcode.org/docs/settings/#dartanalyzerinstrumentationlogfile) and take a copy of it next time this happens?

Note: the log file will get quite large, and will include parts of your source code - if you can repro with a public project that would be best, but otherwise you may need to review and extra the useful parts of the log - which will be from a few lines before the last line that starts with `Req:` after the timestamp. That will help understand what the last few requests sent to the server were.

Thanks!

**Comment by leeprobert** [comment]
I get this issue continuously on my Macbook Pro M1. Hovering over some code just shows `loading...` and does nothing. I have to cancel the dialog that just sits there in the bottom-right, quit, and restart the IDE. But it is getting worse.

**Comment by leidig54** [comment]
> I get this issue continuously on my Macbook Pro M1. Hovering over some code just shows `loading...` and does nothing. I have to cancel the dialog that just sits there in the bottom-right, quit, and restart the IDE. But it is getting worse.

Upgrading to flutter 2.2.2 did fix this for me on an M1 mac

**Comment by DanTup** [comment]
@leeprobert can you confirm you're on the latest Flutter (v2.2.2)? If so, can you try to capture a log (see [this comment](https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-864104286) above yours). Thanks!

**Comment by leeprobert** [comment]
Upgrading fixed this 👍

**Comment by orestesgaolin** [comment]
> @leeprobert can you confirm you're on the latest Flutter (v2.2.2)? If so, can you try to capture a log (see [this comment](https://github.com/Dart-Code/Dart-Code/issues/3270#issuecomment-864104286) above yours). Thanks!

I can confirm that it started to appear again in 2.2.2 after couple of days of flawless work. I'll try to capture some logs, but it's very intermittent issue.

**Comment by leeprobert** [comment]
Hmm, interesting. I'll keep monitoring this. Has been ok since upgrading.

**Comment by orestesgaolin** [comment]
Just to clarify before I'm able to capture logs. The "formatting" takes now with 2.2.2 about 10-15 seconds instead of _indefinite_ time in the 2.2.0/1 

<img width="510" alt="CleanShot 2021-06-29 at 10 08 11@2x" src="https://user-images.githubusercontent.com/16854239/123761339-068b9c80-d8c2-11eb-811e-519f1bff0ee1.png">

**Comment by DanTup** [comment]
@orestesgaolin logs would definitely help. The fix in 2.2.2 should fix the issue where the analysis server never recovered (I think it was a deadlock in the macOS watcher code), but format operations that complete - albeit slowly - are likely a different issue.

Do you know what you were doing just prior to this happening? Had you recently opened the project or modified packages/pubspec? Do you know if it said "Analzying..." in the status bar while this happened?

**Comment by ilkerulusoy** [comment]
I made an update. The problem still persists. I will send log to logs@dartcode.org.

**Comment by DanTup** [comment]
@ilkerulusoy thanks! I checked the log, but it looks like it didn't include the request to format. The log file ends right after the initial analysis completes. Did you try to save/format while initial analysis may still have been in progress? (parts of that analysis are synchronous and will delay formatting until they're complete).

Also - could you see if enabling the `dart.previewLsp` setting to see if that makes any difference? That will soon become the default mode and has some performance advantages (because less of the code has to share a single thread with all other VS Code extensions).

**Comment by ilkerulusoy** [comment]
@DanTup Restarting vscode fixed it. My log setting is active, I'll repost from the next. I didn't make any changes for `dart.previewLsp` in the initial setting. 
I think this event happens after this situation that run real ios device or simulator mixed.

**Comment by sowens-csd** [comment]
I just emailed a log taken during a formatter hang in VSCode. I'm using 2.2.2. The issue is very intermittent for me. The same project will work fine for a week or so and then I'll get a hang. I've had logging turned on for a long time to see if I could catch one in progress. Let me know if the log snippet I sent isn't enough. The whole log was > 700 mb so I only sent the last 200 lines. The formatter was hung for more than three minutes before I closed VSCode and sent the log.

**Comment by DanTup** [comment]
@sowens-csd thanks for the log - unfortunately it doesn't seem to include the formatting request, so it's hard to tell what was going on. Was the formatting _still occurring_ when you took this log? There are lots of requests/responses in the part you sent me, suggesting the server was responsive so I'm not yet sure what might've happened.

If you still have the full log, are you able to search for `/formatting` and see if you can find the format request? Sending everything from a little before that might be useful to understand what's going on. Thanks!

**Comment by sowens-csd** [comment]
I do still have the full log and did a grep for 'formatting' and it doesn't appear in the file `analyzer.txt.1` at all. That's surprising since it spans from Friday morning to this morning. Perhaps I have the logging configured incorrectly? When I took the log I'd closed and restarted VSCode. I figured that the end of this log would represent the state when it shut down, at which time it was still formatting. That word doesn't appear in `analyzer.txt` either.

**Comment by DanTup** [comment]
@sowens-csd that's definitely strange (although perhaps may also be related? 🤔)

A few questions:

- Do you have `dart.enableSdkFormatter: false` in your settings?
- Do you have any other formatters enabled? For example Prettier encourages adding `"editor.defaultFormatter": "esbenp.prettier-vscode",` to your setting which would result in it being called for Dart formatting
- Did the message definitely say it was formatting (and not - for example - running some other action on-save, like Sort Members or Fix All?)

It may also be interesting to run **Dart: Capture Logs** and just force a format operation and see whether that shows up in the log or not.

**Comment by sowens-csd** [comment]
* Do you have dart.enableSdkFormatter: false in your settings?
No

* Do you have any other formatters enabled? For example Prettier encourages adding "editor.defaultFormatter": "esbenp.prettier-vscode", to your setting which would result in it being called for Dart formatting
Not that I know of. Editor: Default Formatter shows `None`. I don't see anything else referenced in the settings.json. 

* Did the message definitely say it was formatting (and not - for example - running some other action on-save, like Sort Members or Fix All?)
Yes, I believe so. Of course just because that's my memory doesn't prove it is so. 

I tried a `Capture Logs` and _formatting_ does not appear in that log when I save a file with format on save turned on nor when I try a `dart format lib/*.dart` from the command line. I'd assume that the save operation triggers a format every time with that setting on? Or is there another way I can ensure it is forced?

**Comment by DanTup** [comment]
@sowens-csd sorry, my mistake - I thought you had LSP enabled but checking the log again it is not. In this case you should be looking for `edit.format` in the log instead (this also doesn't exist in the log you sent me unfortunately).

That said, I would also encourage enabling LSP with the `dart.previewLsp` setting if possible to see whether that makes any difference. That will soon become the default, and improves the performance of some things as it moves more work out of the single thread shared with other VS Code extensions.

To force formatting, you should be able to just insert any unformatted code (eg. `foo() {          }`) and save or run the **Format Document** command from the command palette (and you should see all the spaces disappear if it's working).

> nor when I try a `dart format lib/*.dart` from the command line

Running from the command line or embedded terminal definitely won't show up, as they're completely disconnected from the extension and just work on the filesystem directly.

**Comment by sowens-csd** [comment]
I just sent you a larger log extract that includes the last `edit.format` request and surrounding context. Just out of curiosity I checked the complete log file and there were 77 `edit.format` instances in it. All of them were successful until the last one. Let me know if anything else from that file would be useful. 

I'll give the `dart.previewLsp` another try. I have tried it previously but switched back for reasons that I don't remember. I think it might have been that code completion and help stopped working intermittently. That was in an earlier release though so it's definitely worth another try. I'll keep logging turned on in case I can reproduce again.

**Comment by DanTup** [comment]
In the log you sent me, I only see one `edit.format` but it appears to have completed very quickly (the line immediately following it is the response).

There have been many improvements in LSP in the latest stable releases, and from the next release of the Dart plugin it will be on by default for everyone that hasn't explicitly turned it off (it's currently at 75%). If there are any outstanding issues with it I'd definitely like to know. (I'm not sure it'll make much difference here, but it's certainly worth trying - there's less to go wrong in the VS Code side using LSP, and if things go wrong in the server they're usually more obvious from the logs).

In LSP the formatting is a little different too - we minimise the edits on the server, whereas without we'll send a replacement for the entire file and let VS Code figure it out. Again, I'm not sure it would affect this issue, but it will cut out that extra work being done by VS Code.

**Comment by sowens-csd** [comment]
Thanks for having a look. I've switched to LSP and will post an update if I see the format issue again.

**Comment by AleksandarSavic95** [comment]
Had the same issue with Flutter 2.2.1. After uninstalling Flutter and Dart extensions, upgrading flutter to latest version (now 2.2.3) and reinstalling the extensions, the formatting on save works instantly.
Great job, Flutter/Dart team! 🚀

**Comment by temitopeog** [comment]
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (6 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

**Comment by DanTup** [comment]
@temitopeog can you reproduce it reliably? Is it with particular files? (If so, are you able to share one so that I can reproduce)?

**Comment by temitopeog** [comment]
Hi @DanTup , yes it mostly starts up with a particular file.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:test/misc/colors.dart';
import 'package:test/widgets/app_large_text.dart';
import 'package:test/widgets/app_text.dart';
import 'package:test/model/login_model.dart';

class LoginPage extends StatefulWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
    // email RegExp
  final _emailRegExp = RegExp(
      r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+");

  // uniquely identifies a Form
  final _formKey = GlobalKey<FormState>();

  // holds the form data for access
  final model = LoginModel();
  
  @override
  Widget build(BuildContext context) {
    final double height = MediaQuery.of(context).size.height;
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
    //     padding: const EdgeInsets.only(left: 30, right: 40),
    //     child: Column(
    //       crossAxisAlignment: CrossAxisAlignment.center,
    //       children: [
    //         SizedBox(height: height * 0.1),
    //         Container(
    //           padding: const EdgeInsets.only(left: 0, right: 30),
    //           child: Row(
    //             mainAxisAlignment: MainAxisAlignment.spaceBetween,
    //             children: [
    //               IconButton(
    //                   padding: EdgeInsets.zero,
    //                   constraints: BoxConstraints(),
    //                   icon: Icon(Icons.arrow_back_ios, color: Colors.black54),
    //                   onPressed: () => {}
    //                   // Navigator.of(context, rootNavigator: true)
    //                   //     .pop(context)
    //                   ),
    //               Row(
    //                 mainAxisAlignment: MainAxisAlignment.center,
    //                 children: <Widget>[
    //                   new Container(
    //                     child: new Image.asset(
    //                       'img/icon.png',
    //                       height: 40.0,
    //                       width: 40,
    //                       fit: BoxFit.cover,
    //                     ),
    //                   ),
    //                 ],
    //               ),
    //               Container()
    //             ],
    //           ),
    //         ),
    //         SizedBox(height: height * 0.2),
    //         AppLargeText(text: "Login Now"),
    //         SizedBox(height: height * 0.01),
    //         AppText(text: "Please enter the details below to continue"),
    //         SizedBox(height: height * 0.1),
    //         Container(
    //           width: double.infinity,
    //           child: Container(
    //             decoration: BoxDecoration(color: Colors.white),
    //             child: Column(
    //               children: <Widget>[

    //               ]
    //             )
    //           )
    //         )
    //       ],
    //     ),
      ),
    );
  }
}

**Comment by karascr** [comment]
Removing all package files from the project and deleting local VS Code files (package files etc.) and reinstalling them worked for me idk why.

**Comment by DanTup** [comment]
I can't explain that either, but if you see this come back, please do file a new issue so we can do some digging. Thanks!

**Comment by Cory-FanDemand** [comment]
I am getting this issue alot.  I need to use various flutter versions of flutter including 2.2.0.  Restarting the window with cmd-R  helps at lest temporarily.  

My log file has no error messages:
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.34.0
Flutter extension: 3.34.0 (activated)

App: Visual Studio Code
Version: 1.64.0
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/me/Development/Dev/fvmhome/versions/2.2.1/bin/cache/dart-sdk
    Ver: 2.13.1
Flutter SDK:
    Loc: /Users/me/Development/Dev/fvmhome/versions/2.2.1
    Ver: 2.2.1

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses, DartTest, DAP, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, WebDaemon

Fri Feb 04 2022 [14:23:27 GMT-0500 (Eastern Standard Time)] Log file started
Fri Feb 04 2022 [14:23:58 GMT-0500 (Eastern Standard Time)] Log file ended

**Comment by DanTup** [comment]
@Cory-FanDemand the log you included doesn't seem to have captured anything - did you start capturing before saving/formatting?

I see you're not on the latest version of Flutter (you have v2.2.1, the latest is v2.10). There have been _many_ fixes to the LSP server since then - please try upgrading to the latest version and it may be that the problem goes away.

**Comment by Cory-FanDemand** [comment]
@DanTup   Yes I did, next time it starts happening - if I'm on 2.10 at the time -  I'll try to capture again.

**Comment by DanTup** [comment]
@Cory-FanDemand thanks - you ned to start capturing before the format request is sent (and ideally, leave it for until it completes). You can set logging to run all the time using settings on this page:

https://dartcode.org/docs/logging/#analyzer

Although the files can get quite large, so you should keep an eye on them.

FYI - the analysis server logs will contain parts of your source code, so they may need reviewing/redacting before sharing.

**Comment by grd-certi** [comment]
I was facing the same issue and noticed it would only happen when my internet connection was slow or down. For me, disabling analytics solved the problem:

```sh
dart --disable-analytics
```

**Comment by grlduarte** [comment]
I was facing the same issue and noticed it would only happen when my internet connection was slow or down. For me, disabling analytics solved the problem:

```sh
dart --disable-analytics
```

**Comment by DanTup** [comment]
@grlduarte can you reliably reproduce this? (for example if you manually disconnect your internet, does it occur?)

There are some things I'm aware of where the server will try to connect to the internet (such as caching Pub package names to use in code completion) but I didn't think it was currently sending any analytics. I'm surprised that disabling analytics would fix formatting getting stuck. Has it been long since you disabled them? Is it possible it be intermittent and you've just been lucky since disabling it?

If you can reproduce the issue, I'd be interested in a new issue opening (here or in dart-lang/sdk and CCing me) so we can capture some logs and understand what's happening.

(@bwilkerson FYI)

**Comment by grlduarte** [comment]
@DanTup I have had this problem on and off for some time. Using Vim + [Dart plugin](https://github.com/dart-lang/dart-vim-plugin) I noticed every time my internet was down the editor would stuck on save.

Today I tried what you suggested and: TA-DA. Once the problem was isolated, I don't know what led me to it, but I disabled analytics and the problem was gone.

There's more, I didn't mention in the previous answer but every `dart` command gets stuck with analytics enabled and internet down, even `dart --help`.

Also worth mentioning that my SDK is pretty outdated (2.18.2).

I will open a new issue in dart-lang/sdk since this does not seems to be related to Dart Code

**Comment by DanTup** [comment]
@grlduarte

If this hang still occurs on the latest SDK, I would certainly file an issue in dart-lang/sdk about it. Analytics and no internet should defintely not prevent these commands from working. 

If the `dart language_server` command is hanging, that could certainly also affect editor functionality - although I'd expect far more than formatting to not work, I would expect general editor functionality to suffer too. If you can reproduce issues where general editor functionality (like code completion) works and only formatting is broken in that case, I'd be interested in an additional issue opened here in the Dart-Code repo so we can get some logs to see what's happening there, since it could be a different issue. Thanks!
