### ISSUE TITLE
Debugger is not pausing on breakpoint in Flutter SDK

### ISSUE THREAD

**Issue by nt4f04uNd** [Dart-Code/Dart-Code#3322]
**Describe the bug**
Breakpoint set in SDK not wokring

**To Reproduce**

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox();
  }
}
```

1. open this code sample in Flutter project VSCode
2. got to `SizedBox` definition, set breakpoint somewhere, for example in `createRenderObject` method
3. run app and see that breakpoint is not triggered

**Expected behavior**
Debugger should pause on breakpoint in SDK

**Screenshots**
n/a

**Versions (please complete the following information):**
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.229, on Microsoft Windows [Version 10.0.19041.928], locale ru-RU)
    • Flutter version 2.3.0-1.0.pre.229 at c:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision 14d5eab43c (11 hours ago), 2021-05-05 21:51:53 -0700
    • Engine revision 378e4dbc41
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment]
Debug depth is `Debug my code + packages + SDK`

**Comment by DanTup** [comment]
I tested this on macOS with the iOS simulator, but the breakpoint was hit as expected:

<img width="636" alt="Screenshot 2021-05-06 at 17 47 44" src="https://user-images.githubusercontent.com/1078012/117335585-38205280-ae93-11eb-91ae-768f4afe4933.png">

Are you able to capture a log to help debug?

- Open the small sample app with the code above and add the breakpoint in the right location
- Run the **Dart: Capture Debugging Logs** command from the VS Code command palette
- Run the app and wait for the breakpoint to be missed
- Click **Cancel** on the logging notification to stop logging and open the log file

You can attach the log here, paste into a gist, or email it to me at logs@dartcode.org.

Thanks!

**Comment by nt4f04uNd** [comment]
[Dart-Code-Log-2021-04-04 20-02-04.txt](https://github.com/Dart-Code/Dart-Code/files/6436427/Dart-Code-Log-2021-04-04.20-02-04.txt)

**Comment by DanTup** [comment]
Thanks! It's not clear what's wrong from there - is it possible you could add a breakpoint to your main script file and then _step into_ some code in the `SizedBox` class, while capturing a log? I wonder if there's a miamtch between the URI the VM expects and the one we're sending. Stepping into the file should show the VMs URIs up in the logs.

Thanks!

**Comment by nt4f04uNd** [comment]
What should I do after I step in? Resume an stop capturing the log?

**Comment by nt4f04uNd** [comment]
Here it is

[Dart-Code-Log-2021-04-04 20-18-36.txt](https://github.com/Dart-Code/Dart-Code/files/6436516/Dart-Code-Log-2021-04-04.20-18-36.txt)

**Comment by DanTup** [comment]
I wonder if this is drive-letter-casing related. The breakpoint is being sent like this:

```
{
	"id": "565",
	"jsonrpc": "2.0",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "isolates/1337156570532291",
		"scriptUri": "file:///C:/dev/src/flutter/packages/flutter/lib/src/widgets/basic.dart",
		"line": 2241
	}
}
```
In the log I noticed the invocation of Flutter has a lowercase drive letter (we've had some issues with different casing of drive letters in the past):

```
[20:18:36] [FlutterRun] [Info] [dev] Spawning c:\dev\src\flutter\bin\flutter.bat with args ["run","--machine","--target" // snip
```

Could you try setting the `dart.flutterSdkPath` path in your VS Code user settings to `"C:\dev\src\flutter"` (note the capital C for the drive letter) and reload VS Code and see if that makes any difference? If so, the fix is likely that we should normalise the SDK drive letter to match the rest of the normalised paths.

Thanks!

**Comment by nt4f04uNd** [comment]
In settings I added `"dart.flutterSdkPath": "C:\\dev\\src\\flutter"`
Unfortunately, this doesn't help

[Dart-Code-Log-2021-04-05 18-31-36.txt](https://github.com/Dart-Code/Dart-Code/files/6442761/Dart-Code-Log-2021-04-05.18-31-36.txt)

**Comment by nt4f04uNd** [comment]
Actually, this happens to any package outside the project workspace, not only Flutter SDK

**Comment by bkonyi** [comment]
@DanTup sorry for the delay; I've been OOO.

It would be useful if we could dump the contents of a `getScriptList` RPC response to see which URIs are associated with which scripts and if they match what we're sending to the VM. My guess is that we could set breakpoints successfully if we used the package URI, but not when we use a file URI. If we can narrow it down to that, I can dig around in the VM and see what we can do.

**Comment by DanTup** [comment]
@bkonyi won't the script list just include the same info as above (the package URI, but not the file URI)? Is there any way to see the set of file paths the VM knows about?

> My guess is that we could set breakpoints successfully if we used the package URI

I suspect that's the case too, although it's probably not easy to confirm without adding code to Dart-Code to do the mapping and send them (something we used to do but removed because it relied on parsing the packages file from TypeScript - although with the Dart DAP, perhaps is less of an issue).

**Comment by bkonyi** [comment]
It's possible that there's more than a single script instance for some objects (e.g., one with a file URI and one with a package URI). It'd be worth seeing the dump just to see what scripts have file URI versions and which ones don't. Not sure if it'll give us more insight, but I think it's a good place to start.

**Comment by nt4f04uNd** [comment]
Hmm, this might have something to do with the project configuration itself. I just ran `flutter create app` and it works fine. Check out if you can reproduce it by cloning this https://github.com/nt4f04uNd/sweyer

**Comment by DanTup** [comment]
@nt4f04uNd I tried to run your app on Windows, but it seems to rely on some Google/Firebase config. Are you able to repro on a project that can easily be run without additional setup? Thanks!

**Comment by nt4f04uNd** [comment]
Sorry, I missed that.
I removed all the Google services in a separate branch. I just tested and I can reproduce it by cloning and checking out to this branch https://github.com/nt4f04uNd/sweyer/tree/breakpoint, so hopefully, you'll be able as well.

I set the breakpoint on `MaterialApp.router()` constructor.
Also - after hot-restrart the breakpoint is being hit.

I have tried to make a small reproducible several times already and had no luck.

**Comment by DanTup** [comment]
Thanks! I was able to reproduce this. It looks like a race condition caused by the app not being paused at startup. I can reproduce this by running the same command VS Code is from the terminal:

```
flutter run --machine --target lib/main.dart -d emulator-5554 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ -v
```

This launches the app, but the `--start-paused` is intended to start it paused until the debugger unpauses it. I'll see if I can find what's going on.

**Comment by DanTup** [comment]
I also was unable to repro this outside of your project - though I was able to strip your project right back to something simple and it still occurred. So I tried deleting the `android` folder and re-created it using `flutter create .`. With that new version, I am unable to reproduce the issue again (`--start-paused` seems to work).

So it seems like it's caused by something inside the `android` folder, but I haven't been able to figure out what (the newly-created `android` folder seems quite different to yours, and I'm not familiar enough to understand what's differences are made by you and which are due to something changing in the SDK).

Would it be difficult for you to recreate your Android folder (by deleting it and re-creating with `flutter create .`) and copy your changes back into it to see whether that resolves the issue? (And if not, it should give us a smaller set of changes that might help isolate what's wrong).

**Comment by DanTup** [comment]
I pushed my smaller repro here:

https://github.com/DanTup/sweyer/tree/breakpoint

It's just deleting almost all of the Flutter code, leaving just a simple screen.

**Comment by nt4f04uNd** [comment]
> Would it be difficult for you to recreate your Android folder (by deleting it and re-creating with flutter create .) and copy your changes back into it to see whether that resolves the issue? (And if not, it should give us a smaller set of changes that might help isolate what's wrong).

This project was created on v1.7.8 https://github.com/flutter/flutter/commit/20e59316b8b8474554b38493b8ca888794b0234a

I didn't change any config files, except for gradle (or at least I can't recall this today). Anyways, I can confirm the bug goes away after recreating the Android folder. I'll try to figure out what's going on here too

**Comment by nt4f04uNd** [comment]
Submitted an example repro with some commets as https://github.com/DanTup/sweyer/pull/1
I'm still not sure what exactly causes this

**Comment by DanTup** [comment]
@nt4f04uNd that's for digging! I think you are probably right - I suspect it's caused by this:

```
flutterEngine.getDartExecutor().executeDartEntrypoint(DartExecutor.DartEntrypoint.createDefault());
```

This seems like it will unconditionally run the Dart code, which means `--start-paused` is having no effect, and that creates a race condition where the code may run before we've finished sending the breakpoints to the VM.

I think the only options would be to have it fixed in the Audio plugin (I don't know how simple that would be), or as a workaround you could perhaps detect when running in debug mode and delay that code (either in the Android code, or in your Dart main method by inserting a small delay) to allow breakpoints to be sent so that breakpoints aren't missed.

**Comment by nt4f04uNd** [comment]
cc @ryanheise

**Comment by ryanheise** [comment]
@DanTup happy to fix this in audio_service, and perhaps the documentation in [FlutterActivity](https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html) on how to pre-warm a FlutterEngine could be updated:

> The following illustrates how to pre-warm and cache a FlutterEngine:
> 
> ```java
> // Create and pre-warm a FlutterEngine.
> FlutterEngine flutterEngine = new FlutterEngine(context);
> flutterEngine.getDartExecutor().executeDartEntrypoint(DartEntrypoint.createDefault());
> ```

Inserting a delay seems fragile, though. How much of a delay do you recommend? Looking at the Flutter source, it looks like the default FlutterEngine is created in the activity's `onCreate` and the dart entrypoint is executed in the activity's `onStart` - is that what creates the necessary delay in the default engine setup?

**Comment by DanTup** [comment]
> Inserting a delay seems fragile, though. How much of a delay do you recommend? 

To be clear - my suggestion of a delay was a workaround and only for debugging purposes - I would not recommend it in production.

> perhaps the documentation in FlutterActivity on how to pre-warm a FlutterEngine could be updated:

I agree - although unfortunately I don't know enough about this to know what the ideal fix is. I would recommend filing an issue at https://github.com/flutter/flutter/ describing the issue (that using the code above prevents `--start-paused` from working, and introduces a race condition for IDEs setting up breakpoints and debug settings) and hopefully someone on the Flutter team will have a good answer.

**Comment by nt4f04uNd** [comment]
Filed https://github.com/flutter/flutter/issues/91950

**Comment by DanTup** [comment]
Thanks!
