### ISSUE TITLE
Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by medz** [Dart-Code/Dart-Code#3738]
**Describe the bug**
The file compiled by the normal file reference tool reports an error! Specifically gRPC

Sometimes it is obviously imported correctly, but the type is displayed as dynamic in the code hint. Use shortcut keys to fix duplicate import

**To Reproduce**
1. Create a Dart server project
2. import grpc
3. Edit proto files
4. Using `protoc` build dart output.

**Expected behavior**
After recompiling the protos file, it is normal!

**Screenshots**

![image](https://user-images.githubusercontent.com/5564821/146632775-799fe80d-be6a-4c4a-90e3-5b1c4bcb94d9.png)
![image](https://user-images.githubusercontent.com/5564821/146632871-36ca1d7c-e05f-4e14-88f5-4b25e413d65f.png)

**Versions (please complete the following information):**
 - VS Code version: 版本: 1.63.2 899d46d82c4c95423fb7e10e68eba52050e30ba3
 - Dart extension version: v3.29.0
 - Dart/Flutter SDK version: Dart from Flutter 2.8.0

**Comment by medz** [comment]
The command line is completely correct, but the Dart extension of VS code reports an error. The code is completely fine, and the initial judgment is a problem with Dart's expansion.

You can go to the [repository](https://github.com/socfony/server/tree/dart) of this code, run `build_protos.sh` under tools to recompile protos and it will appear.

**Comment by medz** [comment]
https://user-images.githubusercontent.com/5564821/146633253-d4046ab8-a06f-4a02-85e7-179616f38665.mov

**Comment by DanTup** [comment]
@medz sorry for the delay, I missed the notification for this one. I checked out the latest version of `master` of that repo, but was unable to trigger the issue. Is there a specific commit or SDK version I need to use to repro? Thanks!

**Comment by medz** [comment]
> @medz sorry for the delay, I missed the notification for this one. I checked out the latest version of `master` of that repo, but was unable to trigger the issue. Is there a specific commit or SDK version I need to use to repro? Thanks!

@DanTup In order to avoid this problem, I merged multiple proto files into one and it no longer appears! Currently working well. But compiling multiple files will still trigger occasionally, you can look at the code under this commit https://github.com/socfony/server/tree/bbb6d566539f640e0dad412d8c416c71f159de04

**Comment by DanTup** [comment]
@medz still no luck using that commit. Can you still reproduce it? If so, could you enable the [analyzer instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and reproduce, then see if there's a full error printed into the log?

(don't forget to disable the logging afterwards, as the log files can get quite large).

Thanks!
