### ISSUE TITLE
Stacktrace links not clickable when running Flutter apps on the web

### ISSUE THREAD

**Issue by rodrigo-itao** [Dart-Code/Dart-Code#4418]
**Describe the bug**
The stacktrace links in debug console are not clickable (on Android Studio, the links are clickable).

**To Reproduce**
1. Throw an exception.
2. Try to click the links on the stacktrace.

**Expected behavior**
The links on the stacktrace should be clickable, to open the respective file/line.

**Screenshots**
Stacktrace links not clickable on VSCode:
![image](https://user-images.githubusercontent.com/66178504/222279086-d7c28a75-cb64-4af0-a8b4-c6d4e60f13b4.png)

Stacktrace links clickable on Android Studio:
![image](https://user-images.githubusercontent.com/66178504/222280075-69a35aef-5a2c-424f-ab21-a525f042389e.png)

**Please complete the following information:**
 - Operating System and version: Ubuntu 22.04.2 LTS 5.15.0-60-generic
 - VS Code version: 1.76.0
 - Dart extension version: 3.60.1
 - Dart/Flutter SDK version: flutter 3.7.5, dart 2.19.2
 - Target device (if the issue relates to Flutter debugging): web

**Comment by DanTup** [comment]
@stevemessick does InteliJ/Android Studio have some rules about how it's handling this?

I've filed https://github.com/dart-lang/webdev/issues/949 in the past because I think this should be handled in DWDS (providing proper `package:` or `file:///` URIs so we don't have to make assumptions about how web is laying out packages/SDK files) but if it's not an easy fix there and IntelliJ is already doing its own, maybe we should do the same in the DAP.

**Comment by stevemessick** [comment]
Yes, this is implemented in IntelliJ code in the plugin. IIRC there are several rules applied to convert various forms of links to file positions.

**Comment by saropa** [comment]
Hi, we're having the same issue on both windows and macbook.

    • Operating System and version: Windows 11 (10.0.22621.1992)
    • VS Code version: 1.80.2
    • Flutter (Channel beta, 3.13.0-0.2.pre, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
    • Dart version 3.1.0 (build 3.1.0-262.2.beta)
    • Target device (if the issue relates to Flutter debugging): android

**Comment by FernandoUFS** [comment]
I'm also having the issue for more than 6 months now, it has been very hard to programming this way. I already tried reinstalling everything from scratch, but I had no success.

**Comment by DanTup** [comment]
@saropa @FernandoUFS just to confirm, you're both referring to when running on the web? This issue is web-specific, but there are some other related issues:

- https://github.com/Dart-Code/Dart-Code/issues/4571
- https://github.com/Dart-Code/Dart-Code/issues/4711
- https://github.com/Dart-Code/Dart-Code/issues/4727

**Comment by FernandoUFS** [comment]
@DanTup I'm sorry, I didn't notice the "on the web" on the title either. In my case, the problem happens running on Android, iOS or web.

<img width="1040" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/5408926/26791dce-5285-463b-be86-5f3f3c012ea9">

I have some projects, it happens for all projects, even new ones. I can't click any error to go to file, I have to look the name, open the file and go to the line manually.
In Android Studio works well, but I use vscode.

**Comment by DanTup** [comment]
You didn't miss it, I only added "on the web" to the title today because I realised this one was a bit vague :-)

Some of the non-web issues are solved on Flutter `master` and `beta`, but there are still some outstanding. It's not clear to me exactly which yours are though - if you're able to easily test on current master/beta and let me know (either in new issues, or the linked issues above that seem most relevant) that would be good to know. Thanks!

**Comment by FernandoUFS** [comment]
Now I am using the current master version:
```
Flutter (Channel master, 3.14.0-14.0.pre.220, on macOS 13.5.1 22G90 darwin-arm64, locale en-BR)
```

The files links are still not clickable. Running on Android.

<img width="1040" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/5408926/d10b2c1d-fed4-4e90-aad2-51cbb725619a">

**Comment by DanTup** [comment]
@FernandoUFS are you catching and printing the error yourself, or is Flutter catching it? If the former, then I think you're seeing https://github.com/Dart-Code/Dart-Code/issues/4711

**Comment by saropa** [comment]
We are on the beta channel, and still have this issue on both MacBook and Windows.

The linked issue was reported as having occurred in the last 20 days, but this has been happening for months now.

**Comment by FernandoUFS** [comment]
@DanTup I've created a new project using the last master channel, and I was able to click the exception links in my debug console. I realized that all my projects (around 10 very different projects) that were migrated from flutter 2 have this problem, and as I said, only on vscode. I'm not catching and printing the errors myself. 
Here is a new project:
<img width="899" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/5408926/f5334883-5ef6-4877-b042-ed03d890fb83">

I don't have much time now to figure out what caused this to the migrated project. I remember having this problem since I've started using Flutter 3. But it seems like it's something in my projects. I tried comparing the pubspec.yaml, build.gradle, and bringing the new modifications to one of the migrated projects, yet I couldn't click the errors on debug console. 

If I run in the terminal tab I am able to click on them, but there I lost colors and the hot reload on control + s.

On the next days I will try to create a new flutter project on flutter 3 and copy all the dart code from the old project to see what happens.

**Comment by OthmanShaker** [comment]
same issue for me

**Comment by saropa** [comment]
> @DanTup I've created a new project using the last master channel, and I was able to click the exception links in my debug console. I realized that all my projects (around 10 very different projects) that were migrated from flutter 2 have this problem, and as I said, only on vscode. I'm not catching and printing the errors myself. Here is a new project: <img alt="image" width="899" src="https://user-images.githubusercontent.com/5408926/267944738-f5334883-5ef6-4877-b042-ed03d890fb83.png">
> 
> I don't have much time now to figure out what caused this to the migrated project. I remember having this problem since I've started using Flutter 3. But it seems like it's something in my projects. I tried comparing the pubspec.yaml, build.gradle, and bringing the new modifications to one of the migrated projects, yet I couldn't click the errors on debug console.
> 
> If I run in the terminal tab I am able to click on them, but there I lost colors and the hot reload on control + s.
> 
> On the next days I will try to create a new flutter project on flutter 3 and copy all the dart code from the old project to see what happens.

Ours is also a migrated project - and the timeline matches up for when this issue started occuring. Odd that we didn't notice it right away!

**Comment by DanTup** [comment]
There are a couple of different issues here, I suspect the last few comments above are not related to this one (which is web specific and not new).

I suspect the issue most of you are seeing is https://github.com/Dart-Code/Dart-Code/issues/4571. This was an issue with handling of Flutter exceptions that was preventing them from being linked correctly. This has been fixed recently, but did not ship in the current stable release - it will be included in the next stable release.

The reason that this issue only showed up recently for some, is that this bug only exists in the **new** debug adapters, so you would only have encountered it when you upgraded to a new SDK that included those new debug adapters and you were in the set of users they were enabled for by default.

You can force yourself back on to the legacy debug adapters by adding `"dart.previewSdkDaps": false` to your VS Code settings, but you may miss out in recent new features or bug fixes as all new work is happening in the new debug adapters.

You could also switch to the `beta` channel temporarily to confirm whether the issue is indeed fixed. If you still see issues on `beta`  and it's not because you're `print`ing your own stack traces like in https://github.com/Dart-Code/Dart-Code/issues/4711 (which is not currently supported in the new debug adapters), please let me know **by filing a new issue** with details. Thanks!

**Comment by saropa** [comment]
We are on the debug channel where this is still occuring. 

Seems related to changes / removal of stdout parsing, as mentioned here: https://github.com/Dart-Code/Dart-Code/issues/4711#issuecomment-1706710227

**Comment by adrianvintu** [comment]
Happens to me as well since today - probably.

**Comment by DanTup** [comment]
@martinsellergren 

> On Android, works only if I set "dart.useLegacyDebugAdapters": true.

Could you file a new issue with some examples of this and a repro? This issue is specifically about web because things work a little differently there, but for Android I would expect things to work (except for non-exception stdout content, which is covered by https://github.com/Dart-Code/Dart-Code/issues/4711). Thanks!

**Comment by unknownaloy** [comment]
Is there a resolution for this yet in VSCode?

**Comment by DanTup** [comment]
For web specifically, unfortunately not. Based on comments in https://github.com/dart-lang/webdev/issues/949 I think there may need to be some Flutter work but I'm not familiar with exactly what currently.

If your issue is with non-web, then it's probably covered by one of:

https://github.com/Dart-Code/Dart-Code/issues/5072
https://github.com/Dart-Code/Dart-Code/issues/4711

Which fixes are in-progress for.

**Comment by Andreigr0** [comment]
This helped https://github.com/Dart-Code/Dart-Code/issues/4711#issuecomment-1926837371 but I don't see colors in console, whereas in IntelliJ they're showed

**Comment by DanTup** [comment]
This has been fixed in Flutter master and will be included in a future Flutter release:

https://github.com/user-attachments/assets/ee0c8695-4f1d-4615-9967-b3043eb708b6
