### ISSUE TITLE
Debug Console doesn't add clickable links for stdout output when using new Flutter SDK debug adapters

### ISSUE THREAD

**Issue by Tanthus** [Dart-Code/Dart-Code#4711]
**Describe the bug**
Until about a week ago in the PREVIEW release, clickable code links were showing up on the right side of the "Debug Output" window if the format was using this format:
`<Regular output>  (<package>:<file path>:<line number>:<column number>)`
It was convenient. 

Now the code appears unformatted and unclickable.   I checked to see if there might have been a setting that got turned off but couldn't find anything to enable that feature.

Note the release version of the plugin still works as described

**To Reproduce**
1. Print to the console with say: `print('New route pushed: ServicesRoute (package:app/router.dart:61:9)'`

**Expected behavior**
The above line should produce a clickable link on the right side

**Screenshots**
Release version
![Release version of extension](https://github.com/Dart-Code/Dart-Code/assets/5289174/93770325-f095-404d-b6dc-aa836b2581e4)

Current Pre Release
![Pre Release of extension](https://github.com/Dart-Code/Dart-Code/assets/5289174/4dace64f-a1a5-4dec-a5c0-1cc098267d3e)

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.81.1
 - Dart extension version: v3.71.20230831 pre release
 - Dart/Flutter SDK version: 3.1.0 (stable)
 - Target device (if the issue relates to Flutter debugging): Android

**Comment by DanTup** [comment]
I think you're seeing https://github.com/Dart-Code/Dart-Code/issues/4571 which was fixed via https://github.com/flutter/flutter/pull/131251 but was unfortunately after the cut for the last stable release.

The fix should be in the Flutter beta branch and in the next stable release.

**Comment by Tanthus** [comment]
That is great to hear.   Thank you.   I never thought to try "Structured Errors"  in my searches.

**Comment by Tanthus** [comment]
I noticed that the Code output issues I described above started to appear today.   I noticed that the Dart Plugin updated from 3.70.0 to 3.72.1.     Updated flutter (stable 3.13.1), tried the beta channel of flutter too (beta 3.14.0-0.1.pre), no change.  I then downgraded the Dart plugin back to 3.70.0, which the source code now showed up on the side again.   Just for compleatness I tried the Dart Plugin version 3.72.0, and that didn't work as well as the pre-release version 3.73.20230905.   Also tried a default "flutter create" project with some code, that had the same results.

Anyway, my short-term fix is just to use 3.70.0

Here is the code I used to get the source lines 

`class Log {
	static final Map<int,RegExp> _rxMap = {};

	static String fromSource([int pos=2]) {
		final m = (_rxMap[pos] ?? (_rxMap[pos] = RegExp(r'^\#' '$pos' r'[^\(]*\(([^\)]*)',multiLine: true))).firstMatch(StackTrace.current.toString(),);
		return m == null ? '':m[1]!;
	}

	// Should compile out completely in release mode.
	static void note(Object? obj) {
		if (kDebugMode) {
			print('$obj (${fromSource()})');
		}
	}
}
`

Add a Log.note('something') anywhere and you will get the source where that came from.

**Comment by DanTup** [comment]
Turns out there are two issues here:

1. We don't perform stack trace parsing on stdout output (only known errors)
2. The new debug adapters use `package:stack_trace` to parse stack frames which doesn't parse bare strings in the format given above (whereas the legacy debug adapters did their own parsing and weren't fussy about the format)

The second will need fixing in Dart/DDS and the first may be fixable in either Dart or Flutter depending on whether we want to scan all output (which means making all output asynchronous, since looking up `package:` URIs may involve a call to the VM).

**Comment by Tanthus** [comment]
I understand.   I am doing the stdout formatting as a trick to get the links for my print statements (see code above) primarily for my debug sanity and since it worked.

**Comment by saropa** [comment]
> stdout formatting as a trick

Hi, we are facing this issue too. Could you explaing the trick? I was unable to figure it out from reading above!

**Comment by DanTup** [comment]
The "trick" doesn't work on the new SDK DAPs. Tanthus was printing stack traces so they were in the format that the old debug adapters detected as stack traces and would automatically link up. The new debug adapters are more strict and currently only scanning real errors for stack traces.

**Comment by PedroMGomes** [comment]
Hey, the `"dart.previewSdkDaps": false` is gone on `v3.82.0`, any way to force the previous debug adapters without downgrading the vscode dart extension?
Currently on `3.16.5` Flutter SDK

**Comment by martinsellergren** [comment]
> The "trick" doesn't work on the new SDK DAPs. Tanthus was printing stack traces so they were in the format that the old debug adapters detected as stack traces and would automatically link up. The new debug adapters are more strict and currently only scanning real errors for stack traces.

I can't see links when printing stack traces using dart:developer's log(), or logger-package. It works when setting `"dart.useLegacyDebugAdapters": true`. Is this expected and part of this issue, or is it a new issue? I'm curious what *real errors* mean. 

ref: https://github.com/Dart-Code/Dart-Code/issues/4418#issuecomment-2007108319

**Comment by DanTup** [comment]
@martinsellergren real errors are when there is an exception that is unhandled (so is printed to stderr by Dart) or handled by Flutter (which triggers a "structured error").

If you're printing the stack trace yourself (eg. the debugger doesn't specifically know it's a stack trace, it's just some string output that happens to contain a stack trace) then that's what this issue is covering.

**Comment by martinsellergren** [comment]
> @martinsellergren real errors are when there is an exception that is unhandled (so is printed to stderr by Dart) or handled by Flutter (which triggers a "structured error").
> 
> If you're printing the stack trace yourself (eg. the debugger doesn't specifically know it's a stack trace, it's just some string output that happens to contain a stack trace) then that's what this issue is covering.
> 

Got it, thanks for the explanation. I believe what I'm seeing is another issue then. I'll create a new issue shortly.

**Comment by adrianvintu** [comment]
How can we transform a `print(s)` to stderr, or whatever is required to be interpreted as a stack?

**Comment by DanTup** [comment]
> How can we transform a `print(s)` to stderr, or whatever is required to be interpreted as a stack?

For a Dart application, you could use `stderr.write`/`stderr.writeln` to write directly to the stderr stream. Unfortunately this won't work for Flutter, because the way output streams works for Flutter is different (because the debugger doesn't run the application directly, it runs Flutter, which may run the application on another device).

**Comment by adrianvintu** [comment]
No solution for Flutter (android and ios)? Some workaround?

**Comment by larssn** [comment]
We just migrated to the newest Flutter/Dart today, and are seeing the above, even with Flutter's default error handling.

Not sure how to resolve it. `"dart.useLegacyDebugAdapters": true` does nothing apparently.

```
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.4 on channel stable at /Users/lars/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (6 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lars/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/lars/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)            
    • SM T510 (mobile) • R52N70RYCGL • android-arm    • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by DanTup** [comment]
@adrianvintu 

> Some workaround? This is how we catch errors:

I don't have any good workaround (besides using legacy adapters, but that's not great), but if you only need `Sentry` for release builds, I wonder if you could skip setting `FlutterError.onError` for debug builds so the normal Flutter handling occurs?

@larssn 

> Maybe a restart of VSCode was needed after setting dart.useLegacyDebugAdapters

No restart of VS Code should be required, but you will need to start a new debug session (the setting is read during the debug session start).

Note: Using `useLegacyDebugAdapters` is not a good long-term fix because the legacy adapters are not getting new features as the language evolves.

I do hope to look at this soon, but it needs some refactoring across both Dart + Flutter debug adapters (and because of how the Dart adapter rolls into Flutter, this isn't as straightforward as I'd like).

**Comment by DanTup** [comment]
This is now fixed in the latest Flutter master. Output to `stdout` is scanned for stack frames in the same way as `stderr` and the white links will appear on the right side.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/d5f3b0af-6099-4208-aa7d-ad4490bb1407)

Sorry for the delay/inconvenience!

**Comment by larssn** [comment]
Outstanding!

**Comment by adrianvintu** [comment]
Thank you @DanTup. I removed the Sentry and debugPrint stack. The stack is still not rendered as stack, but as text. There is no option to click on files in the debug view.

**Comment by DanTup** [comment]
@adrianvintu please file a new issue with some code to reproduce the issue you're seeing and a screenshot of what you see. Thanks!
