### ISSUE TITLE
Saving pubspec.yaml produces error if Dart SDK folder contains certain characters

### ISSUE THREAD

**Issue by Porl91** [Dart-Code/Dart-Code#673]
DartCode version: 2.10.0 (Release)
VSCode version: 1.21.0
Dart version: 2.0.0-dev.35.0

If I save the `pubspec.yaml` file of a Dart project (triggering a `pub get`) I receive the error below in the terminal (without it fetching dependencies or creating any files) if the Dart SDK path that I've configured in the User Settings contains '('. The extension appears to detect the correct version in the icon bar however.

This also seems to be the case when executing `pub get` via the VSCode notification when the extension detects there are missing dependencies.

![alt](https://i.imgur.com/ECK9fkx.png)

**Comment by DanTup** [comment]
Very strange! We use `childProcess.spawn` and pass it a path to the process to spawn - I would very much expect it to take care of escaping it if required based on how it's running it :(

https://github.com/Dart-Code/Dart-Code/blob/471583686c47c081eaf9cac45c663857c37de764/src/commands/sdk.ts#L153

Should be easy to fix though!

**Comment by DanTup** [comment]
Actually, docs say that spawn takes a "command", so probably it's correct to not escape things (eg. I may send `ping localhost`).

**Comment by DanTup** [comment]
I think we've fixed this before:

https://github.com/Dart-Code/Dart-Code/commit/da0652a084b0d35890f90ae02a639aab95e5f4a5

Here's where I changed `spawn` to `exec` and lost the quotes:

https://github.com/Dart-Code/Dart-Code/commit/5b9e53b2f20812be0b97f569c503110430cc5842

**Comment by Porl91** [comment]
This should have fixed the issue when using `exec` because you're executing the command as-is. After playing around with this it doesn't seem to fix the issue when using `spawn`. 

Testing this printed out this to the Output tab and didn't fetch any packages:
`[test] pub get`

I did notice that when spawning the process with a shell (passing option `shell: true` to `spawn`) it seemed to fix the issue, although I'd suspect this could have implications for other areas that use this method.

**Comment by DanTup** [comment]
![wtf](https://user-images.githubusercontent.com/1078012/37415006-576f93ba-27a2-11e8-8563-45bebd272411.png)

Apparently running a `.exe` or a `.bat` behaves differently :/

**Comment by DanTup** [comment]
Even setting `shell: true` doesn't work for me (even if I add quotes, and/or escape the parens)..
